### ISSUE TITLE
Published documentation for old version

### ISSUE THREAD

**Issue by edgarcosta** [flintlib/python-flint#146]
https://fredrikj.net/python-flint/ serves documentation for 0.3.0

CC: @fredrik-johansson

**Comment by oscarbenjamin** [comment]
We need to relocate the docs from there. I should add them to readthedocs along with CI to push them automatically.

**Comment by oscarbenjamin** [comment]
Docs are now at:

https://python-flint.readthedocs.io/en/latest/
