### ISSUE TITLE
Best way to cast acb to cmath complex?

### ISSUE THREAD

**Issue by rdguerrerom** [flintlib/python-flint#25]
What is the intended mechanism for casting a flint.acb to a cmath.complex? Furthermore, I need to write a function where a given numpy.array of arguments uses FLINT to evaluate the list of arguments and return a list of numpy.complex with the results.

**Comment by oscarbenjamin** [comment]
This is how to convert to complex:
```
In [14]: z = flint.acb(1 + 1j)

In [15]: z
Out[15]: 1.00000000000000 + 1.00000000000000j

In [16]: complex(z)
Out[16]: (1+1j)
```

**Comment by oscarbenjamin** [comment]
If you want to use arb to calculate something with a numpy array then you can use vectorize:
```python
In [21]: from flint import *

In [22]: import numpy as np

In [23]: acb_sqrt = np.vectorize(lambda a: complex(acb(a).sqrt()))

In [24]: a = np.array([[1, 2], [3, 4]], dtype=complex)

In [25]: acb_sqrt(a)
Out[25]: 
array([[1.        +0.j, 1.41421356+0.j],
       [1.73205081+0.j, 2.        +0.j]])
```
Note that the numpy array doesn't give you anything for speed when you use arb like this so you can also just use arb with a list of lists or something.
