### ISSUE TITLE
Reenable Cirrus CI

### ISSUE THREAD

**Issue by oscarbenjamin** [flintlib/python-flint#66]
I just realised that moving the python-flint repo means that Cirrus CI is no longer enabled.

Previously Cirrus CI was being used to build and test wheels for OSX arm64.

The 0.4.2 release of python-flint does not have any wheels for arm64:
https://pypi.org/project/python-flint/0.4.2/#files

@fredrik-johansson can you reenable Cirrus CI on the repo (or otherwise give me sufficient permissions to do it myself)?

**Comment by fredrik-johansson** [comment]
I've made you admin.

**Comment by oscarbenjamin** [comment]
Thanks. Looks like that is still not quite enough because it is in the flintlib orghanisation. You might have received a "request" notification to enable Cirrus.

**Comment by oscarbenjamin** [comment]
This is working now. Thanks Fredrik
