### ISSUE TITLE
Expose FLINT’s sparse polynomials

### ISSUE THREAD

**Issue by jondo** [flintlib/python-flint#96]
Make sparse polynomials accessible e.g. for use within SymPy, as described in https://oscarbenjamin.github.io/blog/czi/post2.html#using-python-flint .
Quote:
>  The biggest bang-for-buck that SymPy can get from FLINT would be from using FLINT’s sparse multivariate polynomials.

(Sorry if this already happened. I am just a SymPy user, new to python-flint, and would like to stay informed about the development of Oscar's ideas.)

**Comment by oscarbenjamin** [comment]
This is being worked on in #59

**Comment by jondo** [comment]
Thank you for directing me. Feel free to close this as a duplicate,  if you like.

**Comment by oscarbenjamin** [comment]
Multivariate polynomials are now added in gh-132
